version: '3.8'

services:
  database:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5578:5432" # expose 5578 and map it to 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  config-server:
    build:
      context: ./config
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - app-network
    environment:
       CONFIG_SERVER_DB_URL: "${CONFIG_SERVER_DB_URL}"
       PET_DB_PSWD: "${PET_DB_PSWD}"
       PET_DB_USER: "${PET_DB_USER}"


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8785:8785"
    depends_on:
      - database
      - config-server
    networks:
      - app-network
    environment:
      KEY_CLOAK_ISSUER_URI: "${KEY_CLOAK_ISSUER_URI}"
      JWK_SET_URI: "${JWK_SET_URI}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8789:8789"
    networks:
      - app-network

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8787:8080" # expose keyclock on 8787
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: