services:
  database:
    container_name: pet-db
    image: postgres:latest
    ports:
      - "5578:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      - path: /home/ubuntu/env/postgres-env.env
        required: true
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_root_password  # Keep secret handling as necessary
    secrets:
      - db_password
      - db_root_password

  keycloak:
    container_name: pet-keycloak
    image: quay.io/keycloak/keycloak:25.0.4
    command: start-dev
    ports:
      - "8787:8080"
    networks:
      - app-network
    env_file:
      - path: /home/ubuntu/env/keycloak-env.env
        required: true

volumes:
  db_data:

networks:
  app-network:

secrets:
  db_password:
    file: /home/ubuntu/env/db_password.txt
  db_root_password:
    file: /home/ubuntu/env/db_root_password.txt