
services:
  database:
    image: postgres:latest
    ports:
      - "5578:5432" # expose 5578 and map it to 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    environment:
      POSTGRES_USER : "${PET_DB_USER}"
      POSTGRES_PASSWORD : "${PET_DB_PSWD}"
      POSTGRES_DB: "${PET_DB_NAME}"


  config-server:
    build:
      context: ./config
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - app-network
    environment:
       CONFIG_SERVER_DB_URL: "${CONFIG_SERVER_DB_URL}"
       PET_DB_PSWD: "${PET_DB_PSWD}"
       PET_DB_USER: "${PET_DB_USER}"


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8785:8785"
    depends_on:
      - database
      - config-server
    networks:
      - app-network
    environment:
      KEY_CLOAK_ISSUER_URI: "${KEY_CLOAK_ISSUER_URI}"
      JWK_SET_URI: "${JWK_SET_URI}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8789:8789"
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db/keycloakdb
      KC_DB_USERNAME: pet_admin
      KC_DB_PASSWORD: pet_admin
      KC_HOSTNAME: localhost
    depends_on:
      - database
    ports:
      - "8787:8080" # expose keyclock on 8787
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: