
services:
  database:
    image: postgres:latest
    ports:
      - "5578:5432" # expose 5578 and map it to 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    environment:
      POSTGRES_USER : "${PET_DB_USER}"
      POSTGRES_PASSWORD : "${PET_DB_PSWD}"
      POSTGRES_DB: "${PET_DB_NAME}"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db/keycloakdb
      KC_DB_USERNAME: pet_admin
      KC_DB_PASSWORD: pet_admin
      KC_HOSTNAME: localhost
    depends_on:
      - database
    ports:
      - "8787:8080" # expose keyclock on 8787
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: