version: '3.8'

services:
  database:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5578:5432" # expose 5578 and map it to 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  config-server:
    image: your-config-server-image
    ports:
      - "8888:8888"
    networks:
      - app-network

  backend:
    image: your-backend-image
    ports:
      - "8080:8080"
    depends_on:
      - database
      - config-server
    networks:
      - app-network

  frontend:
    image: your-frontend-image
    ports:
      - "3000:3000"
    networks:
      - app-network

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    ports:
      - "8787:8080" # expose keyclock on 8787
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: