version: '3.8'

services:
  database:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5578:5432" # expose 5578 and map it to 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  config-server:
    build:
      context: ./config
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8785:8785"
    depends_on:
      - database
      - config-server
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8789:8789"
    networks:
      - app-network

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    ports:
      - "8787:8080" # expose keyclock on 8787
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: