version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  config-server:
    image: your-config-server-image
    ports:
      - "8888:8888"
    networks:
      - app-network

  backend:
    image: your-backend-image
    ports:
      - "8080:8080"
    depends_on:
      - database
      - config-server
    networks:
      - app-network

  frontend:
    image: your-frontend-image
    ports:
      - "3000:3000"
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8081:8080"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: